app.home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app.init:
    path: /init
    defaults: { _controller: AppBundle:Default:init }

app.shoe.list:
    path: /shoes/list
    defaults: { _controller: AppBundle:Shoe:list }

app.shoe.single:
    path: /shoes/{slug}/detail
    defaults: { _controller: AppBundle:Shoe:list }
