app.home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app.init:
    path: /init
    defaults: { _controller: AppBundle:Default:init }

app.product.list:
    path: /products
    defaults: { _controller: AppBundle:Shoe:list }

app.product.detail:
    path: /products/{slug}
    defaults: { _controller: AppBundle:Shoe:detail }

app.token.new:
    path: /tokens
    defaults: { _controller: AppBundle:Token:new }

app.user.new:
    path: /users
    defaults: { _controller: AppBundle:User:new }

app.cart.add:
    path: /carts/add
    defaults: { _controller: AppBundle:Cart:add }

app.cart.remove:
    path: /carts/{cart}/remove
    defaults: { _controller: AppBundle:Cart:remove }

app.cart.detail:
    path: /carts/{cart}
    defaults: { _controller: AppBundle:Cart:detail }
