app.home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app.init:
    path: /init
    defaults: { _controller: AppBundle:Default:init }

app.product.list:
    path: /products
    defaults: { _controller: AppBundle:Shoe:list }

app.product.detail:
    path: /products/{slug}
    defaults: { _controller: AppBundle:Shoe:detail }

app.token.new:
    path: /tokens
    defaults: { _controller: AppBundle:Token:new }

app.user.new:
    path: /users
    defaults: { _controller: AppBundle:User:new }

app.cart.add:
    path: /cart/add
    defaults: { _controller: AppBundle:Cart:add }
