app.home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app.init:
    path: /init
    defaults: { _controller: AppBundle:Default:init }

app.shoe.list:
    path: /shoes
    defaults: { _controller: AppBundle:Shoe:list }

app.shoe.detail:
    path: /shoes/{slug}
    defaults: { _controller: AppBundle:Shoe:detail }

app.token.new:
    path: /tokens
    defaults: { _controller: AppBundle:Token:new }

app.user.new:
    path: /users
    defaults: { _controller: AppBundle:User:new }
