app.home:
    path: /home


app.shoe.list:
    path: /shoes
    defaults: { _controller: AppBundle:Shoe:list }

app.shoe.single:
    path: /shoes/{slug}
    defaults: { _controller: AppBundle:Shoe:list }
