AppBundle\Entity\Brand:
    type: entity
    table: brand
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
    oneToMany:
        shoes:
            targetEntity: AppBundle\Entity\Shoe
            mappedBy: brand
