AppBundle\Entity\Brand:
    type: entiy
    table: brand
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
    oneToMany:
        shoes:
            targetEntity: Shoe
            mappedBy: category
