AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
            unique: true
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
        position:
            type: integer
    oneToMany:
        shoes:
            targetEntity: AppBundle\Entity\Shoe
            mappedBy: category
    manyToOne:
        parent:
            nullable: true
            targetEntity: AppBundle\Entity\Category
            joinColumn:
                onDelete: CASCADE
