AppBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
        position:
            type: integer
    oneToMany:
        shoes:
            targetEntity: AppBundle\Entity\Shoe
            mappedBy: category
    manyToOne:
        gender:
            targetEntity: AppBundle\Entity\Gender
            inversedBy: categories
