AppBundle\Entity\Color:
    type: entity
    table: color
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
        code:
            type: string
            length: 100
    oneToMany:
        shoeColors:
            targetEntity: AppBundle\Entity\ShoeColor
            mappedBy: color
