AppBundle\Entity\Gender:
    type: entity
    table: gender
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        code:
            type: string
            length: 100
    oneToMany:
        categories:
            targetEntity: AppBundle\Entity\Category
            mappedBy: gender
