AppBundle\Entity\ShoeColor:
    type: entity
    table: shoe_color
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        code:
            type: string
            length: 100
    oneToMany:
        images:
            targetEntity: AppBundle\Entity\ShoeColorImage
            mappedBy: shoeColor
            fetch: EAGER
        sizes:
            targetEntity: AppBundle\Entity\ShoeColorSize
            mappedBy: shoeColor
            fetch: EAGER
    manyToOne:
        shoe:
            targetEntity: AppBundle\Entity\Shoe
            inversedBy: colors
