AppBundle\Entity\ShoeColor:
    type: entiy
    table: shoe_color
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
