AppBundle\Entity\Shoe:
    type: entity
    table: shoe
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
        price:
            type: float
        description:
            type: text
        releaseDate:
            type: date
        position:
            type: integer
        quantity:
            type: integer
    oneToMany:
        colors:
            targetEntity: AppBundle\Entity\ShoeColorImage
            mappedBy: shoe
        sizes:
            targetEntity: AppBundle\Entity\ShoeColorSize
            mappedBy: shoe
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: shoes
        brand:
            targetEntity: AppBundle\Entity\Brand
            inversedBy: shoes
