AppBundle\Entity\ShoeColorSize:
    type: entity
    table: shoe_color_size
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        size:
            type: float
        quantity:
            type: smallint
    manyToOne:
        shoeColor:
            targetEntity: AppBundle\Entity\ShoeColor
            inversedBy: sizes
