AppBundle\Entity\Shoe:
    type: entity
    table: shoe
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
        price:
            type: float
        description:
            type: text
        releaseDate:
            type: date
        position:
            type: integer
            options:
                unsigned: true
                default: 0
        featuredPriority:
            type: integer
            options:
                unsigned: true
                default: 0
        salesCount:
            type: integer
            options:
                unsigned: true
                default: 0
        quantity:
            type: integer
            options:
                unsigned: true
                default: 0
    oneToMany:
        colors:
            targetEntity: AppBundle\Entity\ShoeColor
            mappedBy: shoe
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Category
            inversedBy: shoes
        brand:
            targetEntity: AppBundle\Entity\Brand
            inversedBy: shoes
