AppBundle\Entity\ShoeColorImage:
    type: entity
    table: shoe_color_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        small:
            type: string
            length: 100
        medium:
            type: string
            length: 100
        large:
            type: string
            length: 100
    manyToOne:
        shoeColor:
            targetEntity: AppBundle\Entity\ShoeColor
            inversedBy: images
