AppBundle\Entity\ShoeColor:
    type: entity
    table: shoe_color
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
            gedmo:
                slug:
                    separator: -
                    fields:
                        - name
    oneToMany:
        images:
            targetEntity: AppBundle\Entity\ShoeColorImage
            mappedBy: shoeColor
        sizes:
            targetEntity: AppBundle\Entity\ShoeColorSize
            mappedBy: shoeColor
    manyToOne:
        shoe:
            targetEntity: AppBundle\Entity\Shoe
            inversedBy: shoeColors
        color:
            targetEntity: AppBundle\Entity\Color
            inversedBy: shoeColors
