AppBundle\Entity\ShoeColorImage:
    type: entity
    table: shoe_color_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        position:
            type: integer
        sm:
            type: string
            length: 100
        md:
            type: string
            length: 100
        lg:
            type: string
            length: 100
        xl:
            type: string
            length: 100
    manyToOne:
        shoeColor:
            targetEntity: AppBundle\Entity\ShoeColor
            inversedBy: images
