AppBundle\Entity\Shoe:
    type: entiy
    table: shoe
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        slug:
            type: string
            length: 100
        quantity:
            type: integer
    oneToMany:
        colors:
            targetEntity: Color
    manyToOne:
        gender:
            targetEntity: Gender
